name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      # - name: Start the server
      #   run: npm start

      - name: Start the app with PM2
        run: pm2 start ./root/test-repos-for-cicd/index.js
      - name: Start app with startup server
        run: pm2 startup
      - name: Save config pm2
        run: pm2 save
    

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ubuntu-server }}
        with:
          args: |
            --source=~/test-repos-for-cicd/
            --server=91.200.151.45
            --username=root
            --path=~/test-repos-for-cicd/
