name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2.2.5
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # port: ${{ secrets.SERVER_PORT }}
          source: ${{ github.workspace }}
          target: /test-repos-for-cicd
          args: -avz --delete

