name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start app with PM2
        run: pm2 start npm --name "myapp" -- start

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          # path: test-repos-for-cicd/
        with:
          args: |
            --source=/home/runner/work/test-repos-for-cicd/test-repos-for-cicd/
            --path=/home/runner/work/test-repos-for-cicd/test-repos-for-cicd/
      - name: Reload PM2
        run: pm2 reload myapp


        