name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop running app
        run: pkill node || true

      - name: Start app
        run: npm install
      
      # - name: Start app
      #   run: npm start
        
      - name: SSH into server and update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/test-repos/test-repos-for-cicd
            ls -la
            git pull origin main
            npm install
            npm start

